### ISSUE TITLE
errors in my log

### ISSUE THREAD

**Issue by jus61** [Teh-Dango/Sarge-AI#2]
I have some errors in my log file since the update 2.1.6

http://hastebin.com/sunabuzaze.tex

**Comment by Korwiin** [comment]
Similar errors here - using 2.2.4

http://hastebin.com/ogexepocom.tex

If I were to guess, I would say its an issue when the blacklist for Tanoa safezones.

**Comment by Korwiin** [comment]
commenting out the blacklisted safe zones in sarge/code/map_config/SAR_cfg_grps_tanoa.sqf  made the errors go away.   (lines 50 - 55)   which of course should also cause spawns to occur in "safe zones".

**Comment by jus61** [comment]
Do you also have the error
http://hastebin.com/vohewotuga.tex

**Comment by Teh-Dango** [comment]
Didnt realize people were actually using this for errors. I see no text in any of these links about errors :/

**Comment by Korwiin** [comment]
Haha, yeah it appears the hastebin site has tossed the data

**Comment by Teh-Dango** [comment]
Since the blacklist comments resolved the error I will close this issue. I will also be checking the current state of things to see if it was only an issue with the coords and not the blacklist feature itself.
