### ISSUE TITLE
Does this still work with Exile?

### ISSUE THREAD

**Issue by ghost** [Teh-Dango/Sarge-AI#5]
I'm just testing it out on my exile server and I'm not getting any AI spawning at all...

Also I've made (still tweaking) a grid for Vis http://steamcommunity.com/sharedfiles/filedetails/?id=1120714022 Would you be interested in adding it for other people, once I've finished making it?

**Comment by Teh-Dango** [comment]
I have no problems with that at all. It should still work with Exile. Can you post some logs snippets for review?

**Comment by obermaig** [comment]
file fn_preInit.sqf is Typo in the Line 54 (case "exile" - section :

case "exile": {
		
		SAR_AI_friendly_side = INDEPENDENT;
	**HERE->**	AR_AI_unfriendly_side = WEST;
		
		WEST setFriend [INDEPENDENT, 0];
	};

**Comment by Teh-Dango** [comment]
I no longer host exile so if you want to make that typo change and let us know if it works.

**Comment by Teh-Dango** [comment]
Please use the dev branch and let me know if it works.

**Comment by obermaig** [comment]
Hi, i have tested the fix on our exile reborn server, all works correctly

**Comment by Teh-Dango** [comment]
Thanks @obermaig
