### ISSUE TITLE
Typo in prod branche

### ISSUE THREAD

**Issue by obermaig** [Teh-Dango/Sarge-AI#7]
The latest version of sarge-ai system have a typo in sarge\init\fn_postinit.sqf, Line 37:

** HERE--->**  _modConfigs= toLower (isClass (configFile >> "CfgMods" >> _x));
i have no Idea, how to get a CfgMods in toLower Format, but in this Line that is unfortunately not correct...
Should be:  
_modConfigs =isClass (configFile >> "CfgMods" >> _x);	

otherwise you will get errors in RPT and System dont works:
10:05:23   Error position: <toLower (isClass (configFile >> "CfgMods>
10:05:23   Error tolower: Type Bool, expected String
10:05:23 File addons\sarge\init\fn_postInit.sqf, line 37

Greeting
Ober

**Comment by Teh-Dango** [comment]
Ok I will take a look and see what needs to be fixed.

**Comment by Teh-Dango** [comment]
Very good eye. I have changed it to what I thought I did the first time lol. This push should fix the typo.

**Comment by Teh-Dango** [comment]
@obermaig I will mark this closed since I fixed the typo but if you see something else related to this please let me know.
